# demo: --db.username=root --db.password=root --init=always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anyi
    username: ${db.username}
    password: ${db.password}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      # 导入初始数据需赋值 always
      mode: ${init:never}

logging:
  level:
    icu.agony.anyi: info
  file:
    name: ${anyi.workspace:${user.home}/anyi/logs}/anyi.log
